---
title: "Stroop"
author: "Ethan Weed"
date: "4/6/2020"
output:
  html_document:
    code_folding: hide
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = T,  message=FALSE, warning = F}
# Load packages for data handling and plotting
pacman::p_load(tidyverse)


# clear global environment
rm(list = ls())

# read in the data
df <- read.csv("/Users/ethan/Documents/GitHub/ethanweed.github.io/r-tutorials/data/Stroop-raw-over-the-years.csv")
df$Year <- NULL

# make a new dataframe with the same data in the "long" format.
#df <- gather(df, key = "Condition", value = "Time", -Year)

# get condition means and SD's
RT <- colMeans(df)
Stdev <- unname(sapply(df, sd, na.rm = TRUE))
Condition <- colnames(df)

# gather aggregated data in to dataframe
data <- data.frame(Condition, RT, Stdev)


```


```{r echo = T,  message=FALSE, warning = F}
# make a barplot with error bars
ggplot(data, aes(x = Condition, y = RT)) +
  geom_col() +
  geom_errorbar(ymax =RT + Stdev, ymin = RT - Stdev) +
  ylim(0,15) +
  labs(title = "Stroop Results",
       y = "RT (sec)") +
  theme_classic()



```

```{r echo = T,  message=FALSE, warning = F}
# calculate ANOVA
pacman::p_load(lmerTest, pander)


df <- read.csv("/Users/ethan/Documents/GitHub/ethanweed.github.io/r-tutorials/data/Stroop-raw-over-the-years.csv")

df$ID <- seq(1:length(df$Naming_Int))

df_long <- gather(df, key = "Condition", value = "Time", -Year, -ID)

# set up column with task categories
df_long$Task <- ifelse(df_long$Condition == 'Reading_Int' 
                       | df_long$Condition == 'Reading_NoInt', 
                       "Reading", "Naming")
df_long$Interference <- ifelse(df_long$Condition == 'Reading_Int' 
                               | df_long$Condition == 'Naming_Int', 
                               'Interference', 'No_Interference')


# Define our model. Here, we are predicting Time as modeled by Task, Interference, 
#and the interaction of Task and Interference. We are modelling ID as a "random effect".

mod <- lmer(Time ~ Task + Interference + Task*Interference + (1|ID), data=df_long)
ans <- anova(mod)

# Display the ANOVA results in a nice table
library(pander)
pander(ans)
```
